version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file ./consumer/template.yml --s3-bucket lambda-code-storage1 --output-template-file packaged-template.yml
      - sam package --template-file ./producer/template.yml --s3-bucket lambda-code-storage1 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml