version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file template.yml
artifacts:
  type: zip
  files:
    - quotes.yml